version: '3'
services:
  front:
    build:
      context: ./calculator-app-frontend
    container_name: frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BASE_URL
  server:
    build:
      context: ./calculator-app-backend
    container_name: backend
    restart: unless-stopped
    ports:
      - "5000:5000"
