version: '3'
services:
  # front:
  #   build:
  #     context: ./calculator-app-frontend
  #   container_name: frontend
  #   restart: unless-stopped
  #   ports:
  #     - "4200:4200"
  server:
    build:
      context: ./calculator-app-backend
    container_name: backend
    restart: unless-stopped
    ports:
      - "3000:3000"